### ISSUE TITLE
KiCad version

### ISSUE THREAD

**Issue by vzreagle** [cnlohr/cnixxi#11]
Hi, I'm using KiCad 5.1.5 on Ubuntu 20.04 and can't open the schematics. Which version you are using? Thanks, nice project!

**Comment by vzreagle** [comment]
Yes, I can use the PDF and make my own design, because I want to use only your high voltage generator for another function. But I want to know exactly what transistor you used, because I looked for one with similar characteristics (MOSFET N-CHANNEL 200V 1A) on Mouser and Digikey, and they are very expensive and with packages that do not work for me. Did you buy it at LCSC? could you provide the link? Thanks

**Comment by cnlohr** [comment]
You can look into the production files here https://github.com/cnlohr/cnixxi/blob/master/nixitest1/nixitest1-revB.zip

The inner CSV has the BOM.

[nixitest1.csv](https://github.com/cnlohr/cnixxi/files/14289801/nixitest1.csv)

I ended up going with a C2938374 for the high-power switch and C845589 for the individual segments.
